#! /usr/bin/python3
from turtle import *
#Only after disaster can we be resurrected” -Tyler Durden.
colours={'mud':'#663300','lightmud':'#cc9900','bright':'#ffff00',
         'blood':'#ff0000'}
screen=Screen()
screen.setup(1000,1000)
screen.bgcolor(colours['blood'])
dot(1000)
penup()
goto(0,200)
color(colours['bright'])
style =('Times',40,'bold')
pendown()
write('ONLY AFTER',font=style,align='center')
penup()
right(90)
forward(100)
color('#66ffcc')
style =('Times',50,'bold')
pendown()
write('DISASTER',font=style,align='center')
penup()
forward(100)
color('#66ff33')
style =('Times',60,'bold')
pendown()
write('CAN WE BE',font=style,align='center')
penup()
forward(100)
color(colours['blood'])
style =('Times',70,'bold')
pendown()
write('RESURRECTED',font=style,align='center')
penup()

forward(100)
color('#66ccff')
style =('Times',30,'bold')
pendown()
write('-Tyler Durden',font=style,align='center')
hideturtle()
